### ISSUE TITLE
Wallet Connect / Metamask Mobile Signing not working in mint/idgov

### ISSUE THREAD

**Issue by Amosel** [holonym-foundation/zk-frontend#10]
Steps to reproduce:

1. Open https://app.holonym.id/mint/idgov in MacOS safari browser.
2. Scan the Wallet Connect QR code on phone which opens the Metamask app.
3. Connect to holonym by signing message.
4. Sign the second Message.

Expected result - going forward in the UI.
Result - web app still showing 'Please sign the messages in your wallet.'

**Comment by calebtuttle** [comment]
I was not able to reproduce this. I wasn't able to create a wallet in the MetaMask mobile app and so wasn't able to test Wallet Connect QR code with MM. I did try Wallet Connect with the Rainbow Wallet mobile app, and it worked.

Reopen this if you continue to experience the issue.
