### ISSUE TITLE
Add more information for users.

### ISSUE THREAD

**Issue by Amosel** [holonym-foundation/zk-frontend#12]
<img width="1257" alt="Screenshot 2023-02-03 at 10 53 02 AM" src="https://user-images.githubusercontent.com/61532/216555205-ce0bf3c8-3fba-4b0c-b478-c4228f1012cc.png">

Add explanation what is a soul bound token in a hover and with a link like this:
https://vitalik.ca/general/2022/01/26/soulbound.html

**Comment by calebtuttle** [comment]
Closed by ce7ea31251b65f827c4ab8d2ed503b15c51b36ab
